### ISSUE TITLE
error while using github-regexp -s user:maksim-s -q -k

### ISSUE THREAD

**Issue by balook** [gwen001/github-regexp#2]
error : 
```
panic: runtime error: slice bounds out of range [:-13439]

goroutine 117 [running]:
main.printMatch(0xc0007cc000, 0x250d8, 0xc00065a1a0, 0x2, 0x4, 0xc00059c180, 0x7e)
        /home/balu/tools/github-regexp/main.go:324 +0x7db
main.doItem(0xc00022b340, 0x67)
        /home/balu/tools/github-regexp/main.go:303 +0x2a5
main.main.func1(0xc000016b00, 0xc000102780, 0xc00022b340, 0x67)
        /home/balu/tools/github-regexp/main.go:560 +0x7d
created by main.main
        /home/balu/tools/github-regexp/main.go:557 +0xf11
```

**Comment by gwen001** [comment]
Works perfectly for me.
Try to update your Go version.

**Comment by gwen001** [comment]
Problem is about big files returned, like images. Have to find a way to fix that.

**Comment by gwen001** [comment]
Deployed a quick patch, should work now.
